select * from dbo.retail_customer_purchases

-- What is the total revenue generated by male vs female customers

select	
	gender,
	sum(purchase_amount) as revenue
from retail_customer_purchases
group by gender

-- Which customers used a discount but still spent more than average purchase amount?

select
	customer_id,
	purchase_amount
from 
	retail_customer_purchases
where 
	discount_applied = 'Yes'
	and purchase_amount >= (select 
								avg(purchase_amount) 
							from 
								retail_customer_purchases)

-- What are top 5 products with highest average review rating ?

select top 5
	item_purchased,
	round(avg(cast(review_rating as float)),2) as avg_product_rating
from 
	retail_customer_purchases
group by 
	item_purchased
order by 
	avg_product_rating desc

-- Compare average purchase amounts between standard and express shipping

select 
	shipping_type,
	round(avg(purchase_amount),2) as avg_purchase_amount
from 
	retail_customer_purchases
where
	shipping_type in ('Standard' , 'Express')
group by 
	shipping_type
order by 
	avg_purchase_amount desc

-- Do subscribed customers spend more ?

select 
	subscription_status,
	count(customer_id) as total_customers,
	sum(purchase_amount) as total_purchase_amount,
	round(avg(purchase_amount),2) as money_generated_per_customer
from
	retail_customer_purchases
group by 
	subscription_status
order by 
	total_purchase_amount desc, 
	money_generated_per_customer desc;

	
-- Which 5 products have the higest percentage of purchases with discount applied?

select top 5
	item_purchased,
	cast(round(100.0 * sum(case
					when discount_applied = 'Yes' then 1 else 0
				end)
			/ count(*),2) as decimal (10,2))as dependency_on_discount_percent
from 
	retail_customer_purchases
group by 
	item_purchased
order by 
	dependency_on_discount_percent desc;
	
-- Segment customers into new, resturning, loyal based on their total number of previous purchases

with t as (select 
				customer_id,
				previous_purchases,
				case 
					when previous_purchases = 1 then 'new_customer'
					when previous_purchases <=10 then 'returning_customer'
					else 'loyal_customer'
				end as customer_segment
			from retail_customer_purchases
			)

select 
	customer_segment, 
	count(*) as number_of_customers
	from t
	group by customer_segment

-- What are are the top 3 most purchased products within each category?

with t as (select 
				item_purchased,
				category,
				count(customer_id) as total_orders,
			row_number() over(
								partition by category
								order by count(customer_id) desc) as item_rank
			from 
				retail_customer_purchases
			group by 
				category, item_purchased
		)

select  
	item_rank, 
	category, 
	item_purchased, 
	total_orders
from 
	t
where 
	item_rank <=3
	

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select 
		subscription_status,
		count(customer_id)as repeat_buyers
from 
	retail_customer_purchases
where 
	previous_purchases > 5 
group by 
	subscription_status

-- What is the revenue contribution of each age group ?

select 
	age_groups,
	sum(purchase_amount) as total_revenue
from 
	retail_customer_purchases
group by 
	age_groups
order by 
	total_revenue desc
